//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JachtZ.src.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accessory()
        {
            this.AccToBoats = new HashSet<AccToBoat>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Accessory_ID { get; set; }
        public string AccName { get; set; }
        public string DescriptionOfAccessory { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> Inventory { get; set; }
        public Nullable<double> OrderLevel { get; set; }
        public Nullable<double> OrderBatch { get; set; }
        public Nullable<int> Partner_ID { get; set; }
    
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccToBoat> AccToBoats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
